import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import '../modules/rxjs.operators.ts';

export class BjcpStyle{
    code: string;
    category: string;
    style: string;
    styleFamily: string;
    styleHistory: string;
    origin: string;
    abvMin: number;
    abvMax: number;
    ibuMin: number;
    ibuMax: number;
    srmMin: number;
    srmMax: number;
    ogMin: number;
    ogMax: number;
    fgMin: number;
    fgMax: number;

    public constructor(init?: Partial<BjcpStyle>){
        Object.assign(this, init);
    }
}

const styles = [
    new BjcpStyle({
        code: "01A",
        category: "Standard American Beer",
        style: "American Light Lager",
        styleFamily: "Pale Lager",
        styleHistory: "Mass Market Pale Lager",
        origin: "United States",
        abvMin: 2.8,
        abvMax: 4.2,
        ibuMin: 8,
        ibuMax: 12,
        srmMin: 2,
        srmMax: 3,
        ogMin: 1028,
        ogMax: 1040,
        fgMin: 998,
        fgMax: 1008
    }),
    new BjcpStyle({
        code: "01B",
        category: "Standard American Beer",
        style: "American Lager",
        styleFamily: "Pale Lager",
        styleHistory: "Mass Market Pale Lager",
        origin: "United States",
        abvMin: 4.2,
        abvMax: 5.3,
        ibuMin: 8,
        ibuMax: 18,
        srmMin: 2,
        srmMax: 4,
        ogMin: 1040,
        ogMax: 1050,
        fgMin: 1004,
        fgMax: 1010
    }),
    new BjcpStyle({
        code: "01C",
        category: "Standard American Beer",
        style: "Cream Ale",
        styleFamily: "Pale Ale",
        styleHistory: "Indigenous American Beer",
        origin: "United States",
        abvMin: 4.2,
        abvMax: 5.6,
        ibuMin: 8,
        ibuMax: 20,
        srmMin: 2.5,
        srmMax: 5,
        ogMin: 1042,
        ogMax: 1055,
        fgMin: 1006,
        fgMax: 1012
    }),
    new BjcpStyle({
        code: "01D",
        category: "Standard American Beer",
        style: "American Wheat Beer",
        styleFamily: "Wheat Beer",
        styleHistory: "Wheat Beer",
        origin: "United States",
        abvMin: 4,
        abvMax: 5.5,
        ibuMin: 15,
        ibuMax: 30,
        srmMin: 3,
        srmMax: 6,
        ogMin: 1040,
        ogMax: 1055,
        fgMin: 1008,
        fgMax: 1013
    }),
    new BjcpStyle({
        code: "02A",
        category: "International Lager",
        style: "International Pale Lager",
        styleFamily: "Pale Lager",
        styleHistory: "Mass Market Pale Lager",
        origin: "International",
        abvMin: 4.6,
        abvMax: 6,
        ibuMin: 18,
        ibuMax: 25,
        srmMin: 2,
        srmMax: 6,
        ogMin: 1042,
        ogMax: 1050,
        fgMin: 1008,
        fgMax: 1012
    }),
    new BjcpStyle({
        code: "02B",
        category: "International Lager",
        style: "International Amber Lager",
        styleFamily: "Amber Lager",
        styleHistory: "Amber Lager",
        origin: "International",
        abvMin: 4.6,
        abvMax: 6,
        ibuMin: 8,
        ibuMax: 25,
        srmMin: 7,
        srmMax: 14,
        ogMin: 1042,
        ogMax: 1055,
        fgMin: 1008,
        fgMax: 1014
    }),
    new BjcpStyle({
        code: "02C",
        category: "International Lager",
        style: "International Dark Lager",
        styleFamily: "Dark Lager",
        styleHistory: "Dark Lager",
        origin: "International",
        abvMin: 4.2,
        abvMax: 6,
        ibuMin: 8,
        ibuMax: 20,
        srmMin: 14,
        srmMax: 22,
        ogMin: 1044,
        ogMax: 1056,
        fgMin: 1008,
        fgMax: 1012
    }),
    new BjcpStyle({
        code: "03A",
        category: "Czech Lager",
        style: "Czech Pale Lager",
        styleFamily: "Pale Lager",
        styleHistory: "Pilsner",
        origin: "Czech Republic",
        abvMin: 3,
        abvMax: 4.1,
        ibuMin: 20,
        ibuMax: 35,
        srmMin: 3,
        srmMax: 6,
        ogMin: 1028,
        ogMax: 1044,
        fgMin: 1008,
        fgMax: 1014
    }),
    new BjcpStyle({
        code: "03B",
        category: "Czech Lager",
        style: "Czech Premium Pale Lager",
        styleFamily: "Pilsner",
        styleHistory: "Pilsner",
        origin: "Czech Republic",
        abvMin: 4.2,
        abvMax: 5.8,
        ibuMin: 30,
        ibuMax: 45,
        srmMin: 3.5,
        srmMax: 6,
        ogMin: 1044,
        ogMax: 1060,
        fgMin: 1013,
        fgMax: 1017
    }),
    new BjcpStyle({
        code: "03C",
        category: "Czech Lager",
        style: "Czech Amber Lager",
        styleFamily: "Amber Lager",
        styleHistory: "Amber Lager",
        origin: "Czech Republic",
        abvMin: 4.4,
        abvMax: 5.8,
        ibuMin: 20,
        ibuMax: 35,
        srmMin: 10,
        srmMax: 16,
        ogMin: 1044,
        ogMax: 1060,
        fgMin: 1013,
        fgMax: 1017
    }),
    new BjcpStyle({
        code: "03D",
        category: "Czech Lager",
        style: "Czech Dark Lager",
        styleFamily: "Dark Lager",
        styleHistory: "Dark Lager",
        origin: "Czech Republic",
        abvMin: 4.4,
        abvMax: 5.8,
        ibuMin: 18,
        ibuMax: 34,
        srmMin: 14,
        srmMax: 35,
        ogMin: 1044,
        ogMax: 1060,
        fgMin: 1013,
        fgMax: 1017
    }),
    new BjcpStyle({
        code: "04A",
        category: "Pale Malty European Lager",
        style: "Munich Helles",
        styleFamily: "Pale Lager",
        styleHistory: "European Pale Lager",
        origin: "Germany",
        abvMin: 4.7,
        abvMax: 5.4,
        ibuMin: 16,
        ibuMax: 22,
        srmMin: 3,
        srmMax: 5,
        ogMin: 1044,
        ogMax: 1048,
        fgMin: 1006,
        fgMax: 1012
    }),
    new BjcpStyle({
        code: "04B",
        category: "Pale Malty European Lager",
        style: "Festbier",
        styleFamily: "Pale Lager",
        styleHistory: "European Pale Lager",
        origin: "Germany",
        abvMin: 5.8,
        abvMax: 6.3,
        ibuMin: 18,
        ibuMax: 25,
        srmMin: 4,
        srmMax: 7,
        ogMin: 1054,
        ogMax: 1057,
        fgMin: 1010,
        fgMax: 1012
    }),
    new BjcpStyle({
        code: "04C",
        category: "Pale Malty European Lager",
        style: "Helles Bock",
        styleFamily: "Bock",
        styleHistory: "European Pale Lager",
        origin: "Germany",
        abvMin: 6.3,
        abvMax: 7.4,
        ibuMin: 23,
        ibuMax: 35,
        srmMin: 6,
        srmMax: 11,
        ogMin: 1064,
        ogMax: 1072,
        fgMin: 1011,
        fgMax: 1018
    }),
    new BjcpStyle({
        code: "05A",
        category: "Pale Bitter European beer",
        style: "German Leichtbier",
        styleFamily: "Pale Lager",
        styleHistory: "Pilsner",
        origin: "Germany",
        abvMin: 2.4,
        abvMax: 3.6,
        ibuMin: 15,
        ibuMax: 28,
        srmMin: 2,
        srmMax: 5,
        ogMin: 1026,
        ogMax: 1034,
        fgMin: 1006,
        fgMax: 1010
    }),
    new BjcpStyle({
        code: "05B",
        category: "Pale Bitter European beer",
        style: "Kölsch",
        styleFamily: "Pale Ale",
        styleHistory: "Top-Fermented German Lagers",
        origin: "Germany",
        abvMin: 4.4,
        abvMax: 5.2,
        ibuMin: 18,
        ibuMax: 30,
        srmMin: 3.5,
        srmMax: 5,
        ogMin: 1044,
        ogMax: 1050,
        fgMin: 1007,
        fgMax: 1011
    }),
    new BjcpStyle({
        code: "05C",
        category: "Pale Bitter European beer",
        style: "German Helles Exportbier",
        styleFamily: "Pale Lager",
        styleHistory: "European Pale Lager",
        origin: "Germany",
        abvMin: 4.8,
        abvMax: 6,
        ibuMin: 20,
        ibuMax: 30,
        srmMin: 4,
        srmMax: 7,
        ogMin: 1048,
        ogMax: 1056,
        fgMin: 1010,
        fgMax: 1015
    }),
    new BjcpStyle({
        code: "05D",
        category: "Pale Bitter European beer",
        style: "German Pils",
        styleFamily: "Pilsner",
        styleHistory: "Pilsner",
        origin: "Germany",
        abvMin: 4.4,
        abvMax: 5.2,
        ibuMin: 22,
        ibuMax: 40,
        srmMin: 2,
        srmMax: 5,
        ogMin: 1044,
        ogMax: 1050,
        fgMin: 1008,
        fgMax: 1013
    }),
    new BjcpStyle({
        code: "06A",
        category: "Amber Malty European Lager",
        style: "Märzen",
        styleFamily: "Amber Lager",
        styleHistory: "Amber Lager",
        origin: "Germany",
        abvMin: 5.8,
        abvMax: 6.3,
        ibuMin: 18,
        ibuMax: 24,
        srmMin: 8,
        srmMax: 17,
        ogMin: 1054,
        ogMax: 1060,
        fgMin: 1010,
        fgMax: 1014
    }),
    new BjcpStyle({
        code: "06B",
        category: "Amber Malty European Lager",
        style: "Rauchbier",
        styleFamily: "Amber Lager",
        styleHistory: "European Smoked Beer",
        origin: "Germany",
        abvMin: 4.8,
        abvMax: 6,
        ibuMin: 20,
        ibuMax: 30,
        srmMin: 12,
        srmMax: 22,
        ogMin: 1050,
        ogMax: 1057,
        fgMin: 1012,
        fgMax: 1016
    }),
    new BjcpStyle({
        code: "06C",
        category: "Amber Malty European Lager",
        style: "Dunkles Bock",
        styleFamily: "Bock",
        styleHistory: "Bock",
        origin: "Germany",
        abvMin: 6.3,
        abvMax: 7.2,
        ibuMin: 20,
        ibuMax: 27,
        srmMin: 14,
        srmMax: 22,
        ogMin: 1064,
        ogMax: 1072,
        fgMin: 1013,
        fgMax: 1019
    }),
    new BjcpStyle({
        code: "07A",
        category: "Amber Bitter European Beer",
        style: "Vienna Lager",
        styleFamily: "Amber Lager",
        styleHistory: "Amber Lager",
        origin: "Austria",
        abvMin: 4.7,
        abvMax: 5.5,
        ibuMin: 18,
        ibuMax: 30,
        srmMin: 9,
        srmMax: 15,
        ogMin: 1048,
        ogMax: 1055,
        fgMin: 1010,
        fgMax: 1014
    }),
    new BjcpStyle({
        code: "07B",
        category: "Amber Bitter European Beer",
        style: "Altbier",
        styleFamily: "Amber Ale",
        styleHistory: "Top-Fermented German Lagers",
        origin: "Germany",
        abvMin: 4.3,
        abvMax: 5.5,
        ibuMin: 25,
        ibuMax: 50,
        srmMin: 11,
        srmMax: 17,
        ogMin: 1044,
        ogMax: 1052,
        fgMin: 1008,
        fgMax: 1014
    }),
    new BjcpStyle({
        code: "07C",
        category: "Amber Bitter European Beer",
        style: "Pale Kellerbier",
        styleFamily: "Pale Lager",
        styleHistory: "Pilsner",
        origin: "Germany",
        abvMin: 4.7,
        abvMax: 5.4,
        ibuMin: 20,
        ibuMax: 35,
        srmMin: 3,
        srmMax: 7,
        ogMin: 1045,
        ogMax: 1051,
        fgMin: 1008,
        fgMax: 1012
    }),
    new BjcpStyle({
        code: "07C",
        category: "Amber Bitter European Beer",
        style: "Amber Kellerbier",
        styleFamily: "Amber Lager",
        styleHistory: "Amber Lager",
        origin: "Germany",
        abvMin: 4.8,
        abvMax: 5.4,
        ibuMin: 25,
        ibuMax: 40,
        srmMin: 7,
        srmMax: 17,
        ogMin: 1048,
        ogMax: 1054,
        fgMin: 1012,
        fgMax: 1016
    }),
    new BjcpStyle({
        code: "08A",
        category: "Dark European Lager",
        style: "Munich Dunkel",
        styleFamily: "Dark Lager",
        styleHistory: "Dark Lager",
        origin: "Germany",
        abvMin: 4.5,
        abvMax: 5.6,
        ibuMin: 18,
        ibuMax: 28,
        srmMin: 14,
        srmMax: 28,
        ogMin: 1048,
        ogMax: 1056,
        fgMin: 1010,
        fgMax: 1016
    }),
    new BjcpStyle({
        code: "08B",
        category: "Dark European Lager",
        style: "Schwarzbier",
        styleFamily: "Dark Lager",
        styleHistory: "Dark Lager",
        origin: "Germany",
        abvMin: 4.4,
        abvMax: 5.4,
        ibuMin: 20,
        ibuMax: 30,
        srmMin: 17,
        srmMax: 30,
        ogMin: 1046,
        ogMax: 1052,
        fgMin: 1010,
        fgMax: 1016
    }),
    new BjcpStyle({
        code: "09A",
        category: "Strong European Beer",
        style: "Doppelbock",
        styleFamily: "Bock",
        styleHistory: "Bock",
        origin: "Germany",
        abvMin: 7,
        abvMax: 10,
        ibuMin: 16,
        ibuMax: 26,
        srmMin: 6,
        srmMax: 25,
        ogMin: 1072,
        ogMax: 1112,
        fgMin: 1016,
        fgMax: 1024
    }),
    new BjcpStyle({
        code: "09B",
        category: "Strong European Beer",
        style: "Eisbock",
        styleFamily: "Bock",
        styleHistory: "Bock",
        origin: "Germany",
        abvMin: 9,
        abvMax: 14,
        ibuMin: 25,
        ibuMax: 35,
        srmMin: 18,
        srmMax: 30,
        ogMin: 1078,
        ogMax: 1120,
        fgMin: 1020,
        fgMax: 1035
    }),
    new BjcpStyle({
        code: "09C",
        category: "Strong European Beer",
        style: "Baltic Porter",
        styleFamily: "Porter",
        styleHistory: "Porter",
        origin: "Scandinavia",
        abvMin: 6.5,
        abvMax: 9.5,
        ibuMin: 20,
        ibuMax: 40,
        srmMin: 17,
        srmMax: 30,
        ogMin: 1060,
        ogMax: 1090,
        fgMin: 1016,
        fgMax: 1024
    }),
    new BjcpStyle({
        code: "10A",
        category: "German Wheat Beer",
        style: "Weissbier",
        styleFamily: "Wheat Beer",
        styleHistory: "Wheat Beer",
        origin: "Germany",
        abvMin: 4.3,
        abvMax: 5.6,
        ibuMin: 8,
        ibuMax: 15,
        srmMin: 2,
        srmMax: 6,
        ogMin: 1044,
        ogMax: 1052,
        fgMin: 1010,
        fgMax: 1014
    }),
    new BjcpStyle({
        code: "10B",
        category: "German Wheat Beer",
        style: "Dunkles Weissbier",
        styleFamily: "Wheat Beer",
        styleHistory: "Wheat Beer",
        origin: "Germany",
        abvMin: 4.3,
        abvMax: 5.6,
        ibuMin: 10,
        ibuMax: 18,
        srmMin: 14,
        srmMax: 23,
        ogMin: 1044,
        ogMax: 1056,
        fgMin: 1010,
        fgMax: 1014
    }),
    new BjcpStyle({
        code: "10C",
        category: "German Wheat Beer",
        style: "Weizenbock",
        styleFamily: "Wheat Beer",
        styleHistory: "Wheat Beer",
        origin: "Germany",
        abvMin: 6.5,
        abvMax: 9,
        ibuMin: 15,
        ibuMax: 30,
        srmMin: 6,
        srmMax: 25,
        ogMin: 1064,
        ogMax: 1090,
        fgMin: 1015,
        fgMax: 1022
    }),
    new BjcpStyle({
        code: "11A",
        category: "British Bitter",
        style: "Ordinary Bitter",
        styleFamily: "Amber Ale",
        styleHistory: "English Pale Ale",
        origin: "England",
        abvMin: 3.2,
        abvMax: 3.8,
        ibuMin: 25,
        ibuMax: 35,
        srmMin: 8,
        srmMax: 14,
        ogMin: 1030,
        ogMax: 1039,
        fgMin: 1007,
        fgMax: 1011
    }),
    new BjcpStyle({
        code: "11B",
        category: "British Bitter",
        style: "Best Bitter",
        styleFamily: "Amber Ale",
        styleHistory: "English Pale Ale",
        origin: "England",
        abvMin: 3.8,
        abvMax: 4.6,
        ibuMin: 25,
        ibuMax: 40,
        srmMin: 8,
        srmMax: 16,
        ogMin: 1040,
        ogMax: 1048,
        fgMin: 1008,
        fgMax: 1012
    }),
    new BjcpStyle({
        code: "11C",
        category: "British Bitter",
        style: "Strong Bitter",
        styleFamily: "Amber Ale",
        styleHistory: "English Pale Ale",
        origin: "England",
        abvMin: 4.6,
        abvMax: 6.2,
        ibuMin: 30,
        ibuMax: 50,
        srmMin: 8,
        srmMax: 18,
        ogMin: 1048,
        ogMax: 1060,
        fgMin: 1010,
        fgMax: 1016
    }),
    new BjcpStyle({
        code: "12A",
        category: "Pale Commonwealth Beer",
        style: "British Golden Ale",
        styleFamily: "Pale Ale",
        styleHistory: "Pale Ales",
        origin: "England",
        abvMin: 3.8,
        abvMax: 5,
        ibuMin: 20,
        ibuMax: 45,
        srmMin: 2,
        srmMax: 6,
        ogMin: 1038,
        ogMax: 1053,
        fgMin: 1006,
        fgMax: 1012
    }),
    new BjcpStyle({
        code: "12B",
        category: "Pale Commonwealth Beer",
        style: "Australian Sparkling Ale",
        styleFamily: "Pale Ale",
        styleHistory: "Pale Ales",
        origin: "Australian",
        abvMin: 4.5,
        abvMax: 6,
        ibuMin: 20,
        ibuMax: 35,
        srmMin: 4,
        srmMax: 7,
        ogMin: 1038,
        ogMax: 1050,
        fgMin: 1004,
        fgMax: 1006
    }),
    new BjcpStyle({
        code: "12C",
        category: "Pale Commonwealth Beer",
        style: "English IPA",
        styleFamily: "IPA",
        styleHistory: "English Pale Ale",
        origin: "England",
        abvMin: 5,
        abvMax: 7.5,
        ibuMin: 40,
        ibuMax: 60,
        srmMin: 6,
        srmMax: 14,
        ogMin: 1050,
        ogMax: 1075,
        fgMin: 1010,
        fgMax: 1018
    }),
    new BjcpStyle({
        code: "13A",
        category: "Brown British Beer",
        style: "Dark Mild",
        styleFamily: "Brown Ale",
        styleHistory: "English Mild",
        origin: "England",
        abvMin: 3,
        abvMax: 3.8,
        ibuMin: 10,
        ibuMax: 25,
        srmMin: 12,
        srmMax: 25,
        ogMin: 1030,
        ogMax: 1038,
        fgMin: 1008,
        fgMax: 1013
    }),
    new BjcpStyle({
        code: "13B",
        category: "Brown British Beer",
        style: "British Brown Ale",
        styleFamily: "Brown Ale",
        styleHistory: "",
        origin: "England",
        abvMin: 4.2,
        abvMax: 5.4,
        ibuMin: 20,
        ibuMax: 30,
        srmMin: 12,
        srmMax: 22,
        ogMin: 1040,
        ogMax: 1052,
        fgMin: 1008,
        fgMax: 1013
    }),
    new BjcpStyle({
        code: "13C",
        category: "Brown British Beer",
        style: "English Porter",
        styleFamily: "Porter",
        styleHistory: "Porter",
        origin: "England",
        abvMin: 4,
        abvMax: 5.4,
        ibuMin: 18,
        ibuMax: 35,
        srmMin: 20,
        srmMax: 30,
        ogMin: 1040,
        ogMax: 1052,
        fgMin: 1008,
        fgMax: 1014
    }),
    new BjcpStyle({
        code: "14A",
        category: "Scottish Ale",
        style: "Scottish Light",
        styleFamily: "Amber Ale",
        styleHistory: "",
        origin: "Scotland",
        abvMin: 2.5,
        abvMax: 3.2,
        ibuMin: 10,
        ibuMax: 20,
        srmMin: 17,
        srmMax: 22,
        ogMin: 1030,
        ogMax: 1035,
        fgMin: 1010,
        fgMax: 1013
    }),
    new BjcpStyle({
        code: "14B",
        category: "Scottish Ale",
        style: "Scottish Heavy",
        styleFamily: "Amber Ale",
        styleHistory: "",
        origin: "Scotland",
        abvMin: 3.2,
        abvMax: 3.9,
        ibuMin: 10,
        ibuMax: 20,
        srmMin: 13,
        srmMax: 22,
        ogMin: 1035,
        ogMax: 1040,
        fgMin: 1010,
        fgMax: 1015
    }),
    new BjcpStyle({
        code: "14C",
        category: "Scottish Ale",
        style: "Scottish Export",
        styleFamily: "Amber Ale",
        styleHistory: "",
        origin: "Scotland",
        abvMin: 3.9,
        abvMax: 6,
        ibuMin: 15,
        ibuMax: 30,
        srmMin: 13,
        srmMax: 22,
        ogMin: 1040,
        ogMax: 1060,
        fgMin: 1010,
        fgMax: 1016
    }),
    new BjcpStyle({
        code: "15A",
        category: "Irish Beer",
        style: "Irish Red Ale",
        styleFamily: "Amber Ale",
        styleHistory: "Pale Ales",
        origin: "Ireland",
        abvMin: 3.8,
        abvMax: 5,
        ibuMin: 18,
        ibuMax: 28,
        srmMin: 9,
        srmMax: 14,
        ogMin: 1036,
        ogMax: 1046,
        fgMin: 1010,
        fgMax: 1014
    }),
    new BjcpStyle({
        code: "15B",
        category: "Irish Beer",
        style: "Irish Stout",
        styleFamily: "Stout",
        styleHistory: "Irish Stout",
        origin: "Ireland",
        abvMin: 4,
        abvMax: 4.5,
        ibuMin: 25,
        ibuMax: 45,
        srmMin: 25,
        srmMax: 40,
        ogMin: 1036,
        ogMax: 1044,
        fgMin: 1007,
        fgMax: 1011
    }),
    new BjcpStyle({
        code: "15C",
        category: "Irish Beer",
        style: "Irish Extra Stout",
        styleFamily: "Stout",
        styleHistory: "Irish Stout",
        origin: "Ireland",
        abvMin: 5.5,
        abvMax: 6.5,
        ibuMin: 35,
        ibuMax: 50,
        srmMin: 25,
        srmMax: 40,
        ogMin: 1052,
        ogMax: 1062,
        fgMin: 1010,
        fgMax: 1014
    }),
    new BjcpStyle({
        code: "16A",
        category: "Dark British Beer",
        style: "Sweet Stout",
        styleFamily: "Stout",
        styleHistory: "English Stout",
        origin: "England",
        abvMin: 4,
        abvMax: 6,
        ibuMin: 20,
        ibuMax: 40,
        srmMin: 30,
        srmMax: 40,
        ogMin: 1044,
        ogMax: 1060,
        fgMin: 1012,
        fgMax: 1024
    }),
    new BjcpStyle({
        code: "16B",
        category: "Dark British Beer",
        style: "Oatmeal Stout",
        styleFamily: "Stout",
        styleHistory: "English Stout",
        origin: "England",
        abvMin: 4.2,
        abvMax: 5.9,
        ibuMin: 25,
        ibuMax: 40,
        srmMin: 22,
        srmMax: 40,
        ogMin: 1045,
        ogMax: 1065,
        fgMin: 1010,
        fgMax: 1018
    }),
    new BjcpStyle({
        code: "16C",
        category: "Dark British Beer",
        style: "Tropical Stout",
        styleFamily: "Stout",
        styleHistory: "English Stout",
        origin: "England",
        abvMin: 5.5,
        abvMax: 8,
        ibuMin: 30,
        ibuMax: 50,
        srmMin: 30,
        srmMax: 40,
        ogMin: 1056,
        ogMax: 1075,
        fgMin: 1010,
        fgMax: 1018
    }),
    new BjcpStyle({
        code: "16D",
        category: "Dark British Beer",
        style: "Foreign Extra Stout",
        styleFamily: "Stout",
        styleHistory: "Irish Stout",
        origin: "England",
        abvMin: 6.3,
        abvMax: 8,
        ibuMin: 50,
        ibuMax: 70,
        srmMin: 30,
        srmMax: 40,
        ogMin: 1056,
        ogMax: 1075,
        fgMin: 1010,
        fgMax: 1018
    }),
    new BjcpStyle({
        code: "17A",
        category: "Strong British Ale",
        style: "British Strong Ale",
        styleFamily: "Strong Ale",
        styleHistory: "Strong Ale",
        origin: "England",
        abvMin: 5.5,
        abvMax: 8,
        ibuMin: 30,
        ibuMax: 60,
        srmMin: 8,
        srmMax: 22,
        ogMin: 1055,
        ogMax: 1080,
        fgMin: 1015,
        fgMax: 1022
    }),
    new BjcpStyle({
        code: "17B",
        category: "Strong British Ale",
        style: "Old Ale",
        styleFamily: "Strong Ale",
        styleHistory: "Strong Ale",
        origin: "England",
        abvMin: 5.5,
        abvMax: 9,
        ibuMin: 30,
        ibuMax: 60,
        srmMin: 10,
        srmMax: 22,
        ogMin: 1055,
        ogMax: 1088,
        fgMin: 1015,
        fgMax: 1022
    }),
    new BjcpStyle({
        code: "17C",
        category: "Strong British Ale",
        style: "Wee Heavy",
        styleFamily: "Strong Ale",
        styleHistory: "",
        origin: "Scotland",
        abvMin: 6.5,
        abvMax: 10,
        ibuMin: 17,
        ibuMax: 35,
        srmMin: 14,
        srmMax: 25,
        ogMin: 1070,
        ogMax: 1130,
        fgMin: 1018,
        fgMax: 1040
    }),
    new BjcpStyle({
        code: "17D",
        category: "Strong British Ale",
        style: "English Barleywine",
        styleFamily: "Strong Ale",
        styleHistory: "Barleywine",
        origin: "England",
        abvMin: 8,
        abvMax: 12,
        ibuMin: 35,
        ibuMax: 70,
        srmMin: 8,
        srmMax: 22,
        ogMin: 1080,
        ogMax: 1120,
        fgMin: 1018,
        fgMax: 1030
    }),
    new BjcpStyle({
        code: "18A",
        category: "Pale American Ale",
        style: "Blonde Ale",
        styleFamily: "Pale Ale",
        styleHistory: "Indigenous American Beer",
        origin: "United States",
        abvMin: 3.8,
        abvMax: 5.5,
        ibuMin: 15,
        ibuMax: 28,
        srmMin: 3,
        srmMax: 6,
        ogMin: 1038,
        ogMax: 1054,
        fgMin: 1008,
        fgMax: 1013
    }),
    new BjcpStyle({
        code: "18B",
        category: "Pale American Ale",
        style: "American Pale Ale",
        styleFamily: "Pale Ale",
        styleHistory: "American Pale Beer",
        origin: "United States",
        abvMin: 4.5,
        abvMax: 6.2,
        ibuMin: 30,
        ibuMax: 50,
        srmMin: 5,
        srmMax: 10,
        ogMin: 1045,
        ogMax: 1060,
        fgMin: 1010,
        fgMax: 1015
    }),
    new BjcpStyle({
        code: "19A",
        category: "Amber and Brown American Beer",
        style: "American Amber Ale",
        styleFamily: "Amber Ale",
        styleHistory: "American Pale Beer",
        origin: "United States",
        abvMin: 4.5,
        abvMax: 6.2,
        ibuMin: 25,
        ibuMax: 40,
        srmMin: 10,
        srmMax: 17,
        ogMin: 1045,
        ogMax: 1060,
        fgMin: 1010,
        fgMax: 1015
    }),
    new BjcpStyle({
        code: "19B",
        category: "Amber and Brown American Beer",
        style: "California Common ",
        styleFamily: "Amber Lager",
        styleHistory: "Indigenous American Beer",
        origin: "United States",
        abvMin: 4.5,
        abvMax: 5.5,
        ibuMin: 30,
        ibuMax: 45,
        srmMin: 10,
        srmMax: 14,
        ogMin: 1048,
        ogMax: 1054,
        fgMin: 1011,
        fgMax: 1014
    }),
    new BjcpStyle({
        code: "19C",
        category: "Amber and Brown American Beer",
        style: "American Brown Ale",
        styleFamily: "Brown Ale",
        styleHistory: "Dark American Beer",
        origin: "United States",
        abvMin: 4.3,
        abvMax: 6.2,
        ibuMin: 20,
        ibuMax: 30,
        srmMin: 18,
        srmMax: 35,
        ogMin: 1045,
        ogMax: 1060,
        fgMin: 1010,
        fgMax: 1016
    }),
    new BjcpStyle({
        code: "20A",
        category: "American Porter and Stout",
        style: "American Porter",
        styleFamily: "Porter",
        styleHistory: "Dark American Beer",
        origin: "United States",
        abvMin: 4.8,
        abvMax: 6.5,
        ibuMin: 25,
        ibuMax: 50,
        srmMin: 22,
        srmMax: 40,
        ogMin: 1050,
        ogMax: 1070,
        fgMin: 1012,
        fgMax: 1018
    }),
    new BjcpStyle({
        code: "20B",
        category: "American Porter and Stout",
        style: "American Stout",
        styleFamily: "Stout",
        styleHistory: "Dark American Beer",
        origin: "United States",
        abvMin: 5,
        abvMax: 7,
        ibuMin: 35,
        ibuMax: 75,
        srmMin: 30,
        srmMax: 40,
        ogMin: 1050,
        ogMax: 1075,
        fgMin: 1010,
        fgMax: 1022
    }),
    new BjcpStyle({
        code: "20C",
        category: "American Porter and Stout",
        style: "Imperial Stout",
        styleFamily: "Stout",
        styleHistory: "English Stout",
        origin: "England",
        abvMin: 8,
        abvMax: 12,
        ibuMin: 50,
        ibuMax: 90,
        srmMin: 30,
        srmMax: 40,
        ogMin: 1075,
        ogMax: 1115,
        fgMin: 1018,
        fgMax: 1030
    }),
    new BjcpStyle({
        code: "21A",
        category: "IPA",
        style: "American IPA",
        styleFamily: "IPA",
        styleHistory: "American Pale Beer",
        origin: "United States",
        abvMin: 5.5,
        abvMax: 7.5,
        ibuMin: 40,
        ibuMax: 70,
        srmMin: 6,
        srmMax: 14,
        ogMin: 1056,
        ogMax: 1070,
        fgMin: 1008,
        fgMax: 1014
    }),
    new BjcpStyle({
        code: "21B",
        category: "IPA",
        style: "Specialty IPA - Belgian IPA",
        styleFamily: "IPA",
        styleHistory: "American Bitter Beer",
        origin: "United States",
        abvMin: 6.2,
        abvMax: 9.5,
        ibuMin: 50,
        ibuMax: 100,
        srmMin: 5,
        srmMax: 15,
        ogMin: 1058,
        ogMax: 1080,
        fgMin: 1008,
        fgMax: 1016
    }),
    new BjcpStyle({
        code: "21B",
        category: "IPA",
        style: "Specialty IPA - Black IPA",
        styleFamily: "IPA",
        styleHistory: "American Bitter Beer",
        origin: "United States",
        abvMin: 5.5,
        abvMax: 9,
        ibuMin: 50,
        ibuMax: 90,
        srmMin: 25,
        srmMax: 40,
        ogMin: 1050,
        ogMax: 1085,
        fgMin: 1010,
        fgMax: 1018
    }),
    new BjcpStyle({
        code: "21B",
        category: "IPA",
        style: "Specialty IPA - Brown IPA",
        styleFamily: "IPA",
        styleHistory: "American Bitter Beer",
        origin: "United States",
        abvMin: 5.5,
        abvMax: 7.5,
        ibuMin: 40,
        ibuMax: 70,
        srmMin: 11,
        srmMax: 19,
        ogMin: 1056,
        ogMax: 1070,
        fgMin: 1008,
        fgMax: 1016
    }),
    new BjcpStyle({
        code: "21B",
        category: "IPA",
        style: "Specialty IPA - Red IPA",
        styleFamily: "IPA",
        styleHistory: "American Bitter Beer",
        origin: "United States",
        abvMin: 5.5,
        abvMax: 7.5,
        ibuMin: 40,
        ibuMax: 70,
        srmMin: 11,
        srmMax: 19,
        ogMin: 1056,
        ogMax: 1070,
        fgMin: 1008,
        fgMax: 1016
    }),
    new BjcpStyle({
        code: "21B",
        category: "IPA",
        style: "Specialty IPA - Rye IPA",
        styleFamily: "IPA",
        styleHistory: "American Bitter Beer",
        origin: "United States",
        abvMin: 5.5,
        abvMax: 8,
        ibuMin: 50,
        ibuMax: 75,
        srmMin: 6,
        srmMax: 14,
        ogMin: 1056,
        ogMax: 1075,
        fgMin: 1008,
        fgMax: 1014
    }),
    new BjcpStyle({
        code: "21B",
        category: "IPA",
        style: "Specialty IPA - White IPA",
        styleFamily: "IPA",
        styleHistory: "American Bitter Beer",
        origin: "United States",
        abvMin: 5.5,
        abvMax: 7,
        ibuMin: 40,
        ibuMax: 70,
        srmMin: 5,
        srmMax: 8,
        ogMin: 1056,
        ogMax: 1065,
        fgMin: 1010,
        fgMax: 1016
    }),
    new BjcpStyle({
        code: "22A",
        category: "Strong American Ale",
        style: "Double IPA",
        styleFamily: "IPA",
        styleHistory: "American Bitter Beer",
        origin: "United States",
        abvMin: 7.5,
        abvMax: 10,
        ibuMin: 60,
        ibuMax: 120,
        srmMin: 6,
        srmMax: 14,
        ogMin: 1065,
        ogMax: 1085,
        fgMin: 1008,
        fgMax: 1018
    }),
    new BjcpStyle({
        code: "22B",
        category: "Strong American Ale",
        style: "American Strong Ale",
        styleFamily: "Strong Ale",
        styleHistory: "Strong Ale",
        origin: "United States",
        abvMin: 6.3,
        abvMax: 10,
        ibuMin: 50,
        ibuMax: 100,
        srmMin: 7,
        srmMax: 19,
        ogMin: 1062,
        ogMax: 1090,
        fgMin: 1014,
        fgMax: 1024
    }),
    new BjcpStyle({
        code: "22C",
        category: "Strong American Ale",
        style: "American Barleywine",
        styleFamily: "Strong Ale",
        styleHistory: "Barleywine",
        origin: "United States",
        abvMin: 8,
        abvMax: 12,
        ibuMin: 50,
        ibuMax: 100,
        srmMin: 10,
        srmMax: 19,
        ogMin: 1080,
        ogMax: 1120,
        fgMin: 1016,
        fgMax: 1030
    }),
    new BjcpStyle({
        code: "22D",
        category: "Strong American Ale",
        style: "Wheatwine",
        styleFamily: "Strong Ale",
        styleHistory: "Barleywine",
        origin: "United States",
        abvMin: 8,
        abvMax: 12,
        ibuMin: 30,
        ibuMax: 60,
        srmMin: 8,
        srmMax: 15,
        ogMin: 1080,
        ogMax: 1120,
        fgMin: 1016,
        fgMax: 1030
    }),
    new BjcpStyle({
        code: "23A",
        category: "European Sour Ale",
        style: "Berliner Weisse",
        styleFamily: "Wheat Beer",
        styleHistory: "German Sour Ale",
        origin: "Germany",
        abvMin: 2.8,
        abvMax: 3.8,
        ibuMin: 3,
        ibuMax: 8,
        srmMin: 2,
        srmMax: 3,
        ogMin: 1028,
        ogMax: 1032,
        fgMin: 1003,
        fgMax: 1006
    }),
    new BjcpStyle({
        code: "23B",
        category: "European Sour Ale",
        style: "Flanders Red Ale",
        styleFamily: "Sour Ale",
        styleHistory: "Belgian Sour Ale",
        origin: "Belgium",
        abvMin: 4.6,
        abvMax: 6.5,
        ibuMin: 10,
        ibuMax: 25,
        srmMin: 10,
        srmMax: 16,
        ogMin: 1048,
        ogMax: 1057,
        fgMin: 1002,
        fgMax: 1012
    }),
    new BjcpStyle({
        code: "23C",
        category: "European Sour Ale",
        style: "Oud Bruin",
        styleFamily: "Sour Ale",
        styleHistory: "Belgian Sour Ale",
        origin: "Belgium",
        abvMin: 4,
        abvMax: 8,
        ibuMin: 20,
        ibuMax: 25,
        srmMin: 15,
        srmMax: 22,
        ogMin: 1040,
        ogMax: 1074,
        fgMin: 1008,
        fgMax: 1012
    }),
    new BjcpStyle({
        code: "23D",
        category: "European Sour Ale",
        style: "Lambic",
        styleFamily: "Wheat Beer",
        styleHistory: "Belgian Sour Ale",
        origin: "Belgium",
        abvMin: 5,
        abvMax: 6.5,
        ibuMin: 0,
        ibuMax: 10,
        srmMin: 3,
        srmMax: 7,
        ogMin: 1040,
        ogMax: 1054,
        fgMin: 1001,
        fgMax: 1010
    }),
    new BjcpStyle({
        code: "23E",
        category: "European Sour Ale",
        style: "Gueuze ",
        styleFamily: "Wheat Beer",
        styleHistory: "Belgian Sour Ale",
        origin: "Belgium",
        abvMin: 5,
        abvMax: 8,
        ibuMin: 0,
        ibuMax: 10,
        srmMin: 3,
        srmMax: 7,
        ogMin: 1040,
        ogMax: 1060,
        fgMin: 1000,
        fgMax: 1006
    }),
    new BjcpStyle({
        code: "23F",
        category: "European Sour Ale",
        style: "Fruit Lambic",
        styleFamily: "Wheat Beer",
        styleHistory: "Belgian Sour Ale",
        origin: "Belgium",
        abvMin: 5,
        abvMax: 7,
        ibuMin: 0,
        ibuMax: 10,
        srmMin: 3,
        srmMax: 7,
        ogMin: 1040,
        ogMax: 1060,
        fgMin: 1000,
        fgMax: 1010
    }),
    new BjcpStyle({
        code: "24A",
        category: "Belgian Ale",
        style: "Witbier",
        styleFamily: "Wheat Beer",
        styleHistory: "Wheat Beer",
        origin: "Belgium",
        abvMin: 4.5,
        abvMax: 5.5,
        ibuMin: 8,
        ibuMax: 20,
        srmMin: 2,
        srmMax: 4,
        ogMin: 1044,
        ogMax: 1052,
        fgMin: 1008,
        fgMax: 1012
    }),
    new BjcpStyle({
        code: "24B",
        category: "Belgian Ale",
        style: "Belgian Pale Ale",
        styleFamily: "Pale Ale",
        styleHistory: "Pale Ales",
        origin: "Belgium",
        abvMin: 4.8,
        abvMax: 5.5,
        ibuMin: 20,
        ibuMax: 30,
        srmMin: 8,
        srmMax: 14,
        ogMin: 1048,
        ogMax: 1054,
        fgMin: 1010,
        fgMax: 1014
    }),
    new BjcpStyle({
        code: "24C",
        category: "Belgian Ale",
        style: "Bière de Garde",
        styleFamily: "Amber Ale",
        styleHistory: "European Farmhouse Beer",
        origin: "France",
        abvMin: 6,
        abvMax: 8.5,
        ibuMin: 18,
        ibuMax: 28,
        srmMin: 6,
        srmMax: 19,
        ogMin: 1060,
        ogMax: 1080,
        fgMin: 1008,
        fgMax: 1016
    }),
    new BjcpStyle({
        code: "25A",
        category: "Strong Belgian Ale",
        style: "Belgian Blond Ale",
        styleFamily: "Pale Ale",
        styleHistory: "Belgian Ale",
        origin: "Belgium",
        abvMin: 6,
        abvMax: 7.5,
        ibuMin: 15,
        ibuMax: 30,
        srmMin: 4,
        srmMax: 7,
        ogMin: 1062,
        ogMax: 1075,
        fgMin: 1008,
        fgMax: 1018
    }),
    new BjcpStyle({
        code: "25B",
        category: "Strong Belgian Ale",
        style: "Saison",
        styleFamily: "Pale Ale",
        styleHistory: "European Farmhouse Beer",
        origin: "Belgium",
        abvMin: 3.5,
        abvMax: 9.5,
        ibuMin: 20,
        ibuMax: 35,
        srmMin: 5,
        srmMax: 22,
        ogMin: 1048,
        ogMax: 1065,
        fgMin: 1002,
        fgMax: 1008
    }),
    new BjcpStyle({
        code: "25C",
        category: "Strong Belgian Ale",
        style: "Belgian Golden Strong Ale",
        styleFamily: "Strong Ale",
        styleHistory: "Belgian Strong Ale",
        origin: "Belgium",
        abvMin: 7.5,
        abvMax: 10.5,
        ibuMin: 22,
        ibuMax: 35,
        srmMin: 3,
        srmMax: 6,
        ogMin: 1070,
        ogMax: 1095,
        fgMin: 1005,
        fgMax: 1016
    }),
    new BjcpStyle({
        code: "26A",
        category: "Trappist Ale",
        style: "Trappist Single",
        styleFamily: "Pale Ale",
        styleHistory: "Belgian Ale",
        origin: "Belgium",
        abvMin: 4.8,
        abvMax: 6,
        ibuMin: 25,
        ibuMax: 45,
        srmMin: 3,
        srmMax: 5,
        ogMin: 1044,
        ogMax: 1054,
        fgMin: 1004,
        fgMax: 1010
    }),
    new BjcpStyle({
        code: "26B",
        category: "Trappist Ale",
        style: "Belgian Dubbel",
        styleFamily: "Amber Ale",
        styleHistory: "Belgian Ale",
        origin: "Belgium",
        abvMin: 6,
        abvMax: 7.6,
        ibuMin: 15,
        ibuMax: 25,
        srmMin: 10,
        srmMax: 17,
        ogMin: 1062,
        ogMax: 1075,
        fgMin: 1008,
        fgMax: 1018
    }),
    new BjcpStyle({
        code: "26C",
        category: "Trappist Ale",
        style: "Belgian Tripel",
        styleFamily: "Strong Ale",
        styleHistory: "Belgian Strong Ale",
        origin: "Belgium",
        abvMin: 7.5,
        abvMax: 9.5,
        ibuMin: 20,
        ibuMax: 40,
        srmMin: 4.5,
        srmMax: 7,
        ogMin: 1075,
        ogMax: 1085,
        fgMin: 1008,
        fgMax: 1014
    }),
    new BjcpStyle({
        code: "26D",
        category: "Trappist Ale",
        style: "Belgian Dark Strong Ale",
        styleFamily: "Strong Ale",
        styleHistory: "Belgian Strong Ale",
        origin: "Belgium",
        abvMin: 8,
        abvMax: 12,
        ibuMin: 20,
        ibuMax: 35,
        srmMin: 12,
        srmMax: 22,
        ogMin: 1075,
        ogMax: 1110,
        fgMin: 1010,
        fgMax: 1024
    }),
    new BjcpStyle({
        code: "27A",
        category: "Historical Beer",
        style: "Gose",
        styleFamily: "Wheat Beer",
        styleHistory: "German Sour Ale",
        origin: "Germany",
        abvMin: 4.2,
        abvMax: 4.8,
        ibuMin: 5,
        ibuMax: 12,
        srmMin: 3,
        srmMax: 4,
        ogMin: 1036,
        ogMax: 1056,
        fgMin: 1006,
        fgMax: 1010
    }),
    new BjcpStyle({
        code: "27A",
        category: "Historical Beer",
        style: "Kentucky Common",
        styleFamily: "Amber Ale",
        styleHistory: "Indigenous American Beer",
        origin: "United States",
        abvMin: 4,
        abvMax: 5.5,
        ibuMin: 15,
        ibuMax: 30,
        srmMin: 11,
        srmMax: 20,
        ogMin: 1044,
        ogMax: 1055,
        fgMin: 1010,
        fgMax: 1018
    }),
    new BjcpStyle({
        code: "27A",
        category: "Historical Beer",
        style: "Lichtenhainer",
        styleFamily: "Wheat Beer",
        styleHistory: "European Smoked Beer",
        origin: "Germany",
        abvMin: 3.5,
        abvMax: 4.7,
        ibuMin: 5,
        ibuMax: 12,
        srmMin: 3,
        srmMax: 6,
        ogMin: 1032,
        ogMax: 1040,
        fgMin: 1004,
        fgMax: 1008
    }),
    new BjcpStyle({
        code: "27A",
        category: "Historical Beer",
        style: "London Brown Ale",
        styleFamily: "Brown Ale",
        styleHistory: "",
        origin: "England",
        abvMin: 2.8,
        abvMax: 3.6,
        ibuMin: 15,
        ibuMax: 20,
        srmMin: 22,
        srmMax: 35,
        ogMin: 1033,
        ogMax: 1038,
        fgMin: 1012,
        fgMax: 1015
    }),
    new BjcpStyle({
        code: "27A",
        category: "Historical Beer",
        style: "Piwo Grodziskie",
        styleFamily: "Wheat Beer",
        styleHistory: "European Smoked Beer",
        origin: "Poland",
        abvMin: 2.5,
        abvMax: 3.3,
        ibuMin: 20,
        ibuMax: 35,
        srmMin: 3,
        srmMax: 6,
        ogMin: 1028,
        ogMax: 1032,
        fgMin: 1006,
        fgMax: 1012
    }),
    new BjcpStyle({
        code: "27A",
        category: "Historical Beer",
        style: "Pre-Prohibition Lager",
        styleFamily: "Pilsner",
        styleHistory: "Pilsner",
        origin: "United States",
        abvMin: 4.5,
        abvMax: 6,
        ibuMin: 25,
        ibuMax: 40,
        srmMin: 3,
        srmMax: 6,
        ogMin: 1044,
        ogMax: 1060,
        fgMin: 1010,
        fgMax: 1015
    }),
    new BjcpStyle({
        code: "27A",
        category: "Historical Beer",
        style: "Pre-Prohibition Porter",
        styleFamily: "Porter",
        styleHistory: "Dark American Beer",
        origin: "United States",
        abvMin: 4.5,
        abvMax: 6,
        ibuMin: 20,
        ibuMax: 30,
        srmMin: 18,
        srmMax: 30,
        ogMin: 1046,
        ogMax: 1060,
        fgMin: 1010,
        fgMax: 1016
    }),
    new BjcpStyle({
        code: "27A",
        category: "Historical Beer",
        style: "Roggenbier",
        styleFamily: "Wheat Beer",
        styleHistory: "Wheat Beer",
        origin: "Germany",
        abvMin: 4.5,
        abvMax: 6,
        ibuMin: 10,
        ibuMax: 20,
        srmMin: 14,
        srmMax: 19,
        ogMin: 1046,
        ogMax: 1056,
        fgMin: 1010,
        fgMax: 1014
    }),
    new BjcpStyle({
        code: "27A",
        category: "Historical Beer",
        style: "Sahti",
        styleFamily: "Wheat Beer",
        styleHistory: "European Farmhouse Beer",
        origin: "Scandinavia",
        abvMin: 7,
        abvMax: 11,
        ibuMin: 7,
        ibuMax: 15,
        srmMin: 4,
        srmMax: 22,
        ogMin: 1076,
        ogMax: 1120,
        fgMin: 1016,
        fgMax: 1020
    }),
    new BjcpStyle({
        code: "28A",
        category: "American Wild Ale",
        style: "Brett Beer",
        styleFamily: "Specialty Beer",
        styleHistory: "Specialty Beer",
        origin: "Specialty Beer",
    }),
    new BjcpStyle({
        code: "28B",
        category: "American Wild Ale",
        style: "Mixed-Fermentation Sour Beer",
        styleFamily: "Specialty Beer",
        styleHistory: "Specialty Beer",
        origin: "Specialty Beer",
    }),
    new BjcpStyle({
        code: "28C",
        category: "American Wild Ale",
        style: "Wild Specialty Beer",
        styleFamily: "Specialty Beer",
        styleHistory: "Specialty Beer",
        origin: "Specialty Beer",
    }),
    new BjcpStyle({
        code: "29A",
        category: "Fruit Beer",
        style: "Fruit Beer",
        styleFamily: "Specialty Beer",
        styleHistory: "Specialty Beer",
        origin: "Specialty Beer",
    }),
    new BjcpStyle({
        code: "29B",
        category: "Fruit Beer",
        style: "Fruit and Spice Beer",
        styleFamily: "Specialty Beer",
        styleHistory: "Specialty Beer",
        origin: "Specialty Beer",
    }),
    new BjcpStyle({
        code: "29C",
        category: "Fruit Beer",
        style: "Specialty Fruit Beer",
        styleFamily: "Specialty Beer",
        styleHistory: "Specialty Beer",
        origin: "Specialty Beer",
    }),
    new BjcpStyle({
        code: "30A",
        category: "Spiced Beer",
        style: "Spice, Herb, or Vegetable Beer",
        styleFamily: "Specialty Beer",
        styleHistory: "Specialty Beer",
        origin: "Specialty Beer",
    }),
    new BjcpStyle({
        code: "30B",
        category: "Spiced Beer",
        style: "Autumn Seasonal Beer",
        styleFamily: "Specialty Beer",
        styleHistory: "Specialty Beer",
        origin: "Specialty Beer",
    }),
    new BjcpStyle({
        code: "30C",
        category: "Spiced Beer",
        style: "Winter Seasonal Beer",
        styleFamily: "Specialty Beer",
        styleHistory: "Specialty Beer",
        origin: "Specialty Beer",
    }),
    new BjcpStyle({
        code: "31A",
        category: "Alternative Fermentables Beer",
        style: "Alternative Grain Beer",
        styleFamily: "Specialty Beer",
        styleHistory: "Specialty Beer",
        origin: "Specialty Beer",
    }),
    new BjcpStyle({
        code: "31B",
        category: "Alternative Fermentables Beer",
        style: "Alternative Sugar Beer",
        styleFamily: "Specialty Beer",
        styleHistory: "Specialty Beer",
        origin: "Specialty Beer",
    }),
    new BjcpStyle({
        code: "32A",
        category: "Smoked Beer",
        style: "Classic Style Smoked Beer",
        styleFamily: "Specialty Beer",
        styleHistory: "Specialty Beer",
        origin: "Specialty Beer",
    }),
    new BjcpStyle({
        code: "32B",
        category: "Smoked Beer",
        style: "Specialty Smoked Beer",
        styleFamily: "Specialty Beer",
        styleHistory: "Specialty Beer",
        origin: "Specialty Beer",
    }),
    new BjcpStyle({
        code: "33A",
        category: "Wood Beer",
        style: "Wood-Aged Beer",
        styleFamily: "Specialty Beer",
        styleHistory: "Specialty Beer",
        origin: "Specialty Beer",
    }),
    new BjcpStyle({
        code: "33B",
        category: "Wood Beer",
        style: "Specialty Wood-Aged Beer",
        styleFamily: "Specialty Beer",
        styleHistory: "Specialty Beer",
        origin: "Specialty Beer",
    }),
    new BjcpStyle({
        code: "34A",
        category: "Specialty Beer",
        style: "Clone Beer",
        styleFamily: "Specialty Beer",
        styleHistory: "Specialty Beer",
        origin: "Specialty Beer",
    }),
    new BjcpStyle({
        code: "34B",
        category: "Specialty Beer",
        style: "Mixed-Style Beer",
        styleFamily: "Specialty Beer",
        styleHistory: "Specialty Beer",
        origin: "Specialty Beer",
    }),
    new BjcpStyle({
        code: "34C",
        category: "Specialty Beer",
        style: "Experimental Beer",
        styleFamily: "Specialty Beer",
        styleHistory: "Specialty Beer",
        origin: "Specialty Beer",
    })
];

@Injectable()
export class BjcpService {
    get(): Observable<BjcpStyle[]> {
        return Observable.from([styles]);
    }
}